#!/bin/sh
set -e

ACTIVE_POOL=${ACTIVE_POOL:-blue}
BLUE_HOST=${BLUE_SERVICE_HOST:-app_blue}
GREEN_HOST=${GREEN_SERVICE_HOST:-app_green}
APP_PORT=${APP_PORT:-3000}
NGINX_CONF=/etc/nginx/conf.d/default.conf

setup_log_files() {
    echo "Setting up log files..."
    
    # Ensure log directory exists and has proper permissions
    mkdir -p /var/log/nginx
    chown -R nginx:nginx /var/log/nginx
    
    # Remove the symlinks if they exist
    if [ -L /var/log/nginx/access.log ]; then
        rm -f /var/log/nginx/access.log
    fi
    if [ -L /var/log/nginx/error.log ]; then
        rm -f /var/log/nginx/error.log
    fi
    
    # Create actual log files if they don't exist
    touch /var/log/nginx/access.log
    touch /var/log/nginx/error.log
    
    # Set proper permissions
    chown nginx:nginx /var/log/nginx/access.log
    chown nginx:nginx /var/log/nginx/error.log
    chmod 644 /var/log/nginx/access.log
    chmod 644 /var/log/nginx/error.log
    
    echo "Log files setup complete:"
    ls -la /var/log/nginx/
}

# Create a custom nginx.conf with our log format in the http context
create_nginx_conf() {
    cat > /etc/nginx/nginx.conf <<'EOF'
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Custom log format for enhanced observability
    log_format extended '[$time_local] $remote_addr "$request" $status '
                        'pool="$upstream_http_x_app_pool" '
                        'release="$upstream_http_x_release_id" '
                        'upstream_status=$upstream_status '
                        'upstream_addr=$upstream_addr '
                        'request_time=$request_time '
                        'upstream_response_time=$upstream_response_time '
                        'bytes_sent=$bytes_sent';

    access_log  /var/log/nginx/access.log  extended;

    sendfile        on;
    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}
EOF
}

generate_server_conf() {
    if [ "$ACTIVE_POOL" = "green" ]; then
        PRIMARY_HOST=$GREEN_HOST
        BACKUP_HOST=$BLUE_HOST
    else
        PRIMARY_HOST=$BLUE_HOST
        BACKUP_HOST=$GREEN_HOST
    fi

    cat > "$NGINX_CONF" <<EOF
# autogenerated by docker-entrypoint.sh - ACTIVE_POOL=${ACTIVE_POOL}

upstream backend_upstream {
    server ${PRIMARY_HOST}:${APP_PORT} max_fails=20 fail_timeout=30s;
    server ${BACKUP_HOST}:${APP_PORT} backup;
}

server {
    listen 8080;
    server_name _;

    # Tight timeouts
    proxy_connect_timeout 3s;
    proxy_send_timeout 10s;
    proxy_read_timeout 10s;

    proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
    proxy_next_upstream_tries 1;
    proxy_next_upstream_timeout 15s;

    location / {
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_pass_header X-App-Pool;
        proxy_pass_header X-Release-Id;

        proxy_set_header Connection "";
        proxy_pass http://backend_upstream;
    }

    location = /_nginx_health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
EOF
}

echo "Setting up log files..."
setup_log_files

echo "Creating nginx configuration with custom log format..."
create_nginx_conf

echo "Generating server config for ACTIVE_POOL=${ACTIVE_POOL} ..."
generate_server_conf

echo "Testing nginx configuration..."
nginx -t

echo "Starting nginx..."
exec nginx -g 'daemon off;'